save

diff --git a/scripts/blog b/scripts/blog
--- a/scripts/blog
+++ b/scripts/blog
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 # A bash script that helps me create notes for my blog
-# by running 'blog zet' or 'blog article' a markdown file is created in the proper directory, with my chosen filename.
 
 HOSTING_REPO="$REPOS/blog/"
 
@@ -20,9 +19,6 @@ open_file() {
 	# Create the file in the specified directory
 	touch "$1/$filename.md"
 
-	# cd into second brain
-	cd "$SECOND_BRAIN" || exit
-
 	# Format the title by removing dashes
 	title=$filename
 	title="${title//-/ }"
@@ -31,27 +27,28 @@ open_file() {
 	echo "---" >>"$1/$filename.md"
 	echo "title: $filename" >>"$1/$filename.md"
 	echo "date: $date" >>"$1/$filename.md"
+	echo "tags:" >> "$1/$filename.md"
 
-	if [[ $2 = "zet" ]]; then
-		echo "tags:" >>"$1/$filename.md"
-		echo "- " >>"$1/$filename.md"
-	fi
-
-	if [[ $2 = "article" ]]; then
-		echo "tags:" >>"$1/$filename.md"
-		echo "- Article" >>"$1/$filename.md"
-	fi
+	# if [[ $2 = "zet" ]]; then
+	# 	echo "tags:" >>"$1/$filename.md"
+	# 	echo "- " >>"$1/$filename.md"
+	# fi
+	#
+	# if [[ $2 = "post" ]]; then
+	# 	echo "tags:" >>"$1/$filename.md"
+	# 	echo "- Article" >>"$1/$filename.md"
+	# fi
 
 	echo "---" >>"$1/$filename.md"
 	echo -en "\n" >>"$1/$filename.md"
 	echo -en "\n" >>"$1/$filename.md"
 	echo -en "\n" >>"$1/$filename.md"
-	echo "## Links:" >>"$1/$filename.md"
-	echo -en "\n" >>"$1/$filename.md"
-	echo "$timestamp" >>"$1/$filename.md"
+	#echo "## Links:" >>"$1/$filename.md"
+	#echo -en "\n" >>"$1/$filename.md"
+	#echo "$timestamp" >>"$1/$filename.md"
 
 	# Open the file in Neovim
-	nvim '+ normal 2GzzA' "$1/$filename.md" -c :NoNeckPain
+	nvim -c 'normal G' "$1/$filename.md"
 
 }
 
@@ -62,7 +59,7 @@ case "$1" in
 # 	get_filename
 #
 # 	# Call the function to create and open the file in the specified directory
-# 	open_file "$REPOS/projects/blog/content/zet" "zet"
+# 	open_file "$REPOS/s/blog/content/zet" "zet"
 #
 # 	;;
 post)
@@ -70,7 +67,7 @@ post)
 	get_filename
 
 	# Call the function to create and open the file in the specified directory
-	open_file "$REPOS/blog/content/posts" "posts"
+	open_file "$REPOS/blog/content/posts" "post"
 	;;
 
 reset)
@@ -84,38 +81,38 @@ pub)
 	# ask for commit message, rebuild the site, push to blog repo, then push to hosting repo
 	read -p "Enter commit message: " commitmessage
 
-	read -p "Would you like to tweet + toot that? (y/n) " will_tweet
+	# read -p "Would you like to tweet + toot that? (y/n) " will_tweet
 
-	if [[ $will_tweet == [Yy]* ]]; then
-		read -p "Enter tags, or press enter to post without tags: " tags
-	fi
+	# if [[ $will_tweet == [Yy]* ]]; then
+	# 	read -p "Enter tags, or press enter to post without tags: " tags
+	# fi
 
-	cd "$REPOS/projects/blog/" || exit
+	cd "$REPOS/blog" || exit
 	rm -rf "$REPOS/blog/public"
 	hugo
 	git add .
 	git commit -m "$commitmessage"
 	git push
 	rm -rf "$HOSTING_REPO*"
-	cp -r "$REPOS"/projects/blog/public/* "$HOSTING_REPO"
+	cp -r "$REPOS"/blog/public/* "$HOSTING_REPO"
 	cd "$HOSTING_REPO" || exit
 	git add .
 	git commit -m "$commitmessage"
 	git push
 
-	if [[ $will_tweet == [Yy]* ]]; then
-		echo "Waiting 10 seconds to allow it to publish before tweeting."
-		sleep 10
-
-		# post to twitter/mastodon without tags
-		if [[ $tags == "" ]]; then
-			tweet
-			toot
-			exit
-		fi
-		tweet "$tags"
-		toot "$tags"
-	fi
+	# if [[ $will_tweet == [Yy]* ]]; then
+	# 	echo "Waiting 10 seconds to allow it to publish before tweeting."
+	# 	sleep 10
+	#
+	# 	# post to twitter/mastodon without tags
+	# 	if [[ $tags == "" ]]; then
+	# 		tweet
+	# 		toot
+	# 		exit
+	# 	fi
+	# 	tweet "$tags"
+	# 	toot "$tags"
+	# fi
 	;;
 
 "")
@@ -124,8 +121,8 @@ pub)
 	;;
 
 *)
-	# Print an error message if the parameter was not "zet" or "article"
-	echo "Error: Invalid parameter. Usage: blog zet|article|pub"
+	# Print an error message if the parameter was not used
+	echo "Error: Invalid parameter. Usage: blog post|pub|reset"
 	;;
 esac
 
