save

diff --git a/scripts/inbox b/scripts/inbox
--- a/scripts/inbox
+++ b/scripts/inbox
@@ -5,14 +5,35 @@ if [ -z "$1" ]; then
   exit 1
 fi
 
-file_name=$(echo "$1" | tr ' ' '-')
-formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md
-if [[ $(uname -n) == "DTM017" ]]; then
-    cd "$HOME/Documents/obsd" || exit
-fi
-if [[ $(uname -n) == "wilco" ]]; then
-    cd "$HOME/Documents/obsd" || exit
-fi
+# case "$1" in
+#
+# work)
+#   cd "$HOME/Documents/obsd" || exit
+#   touch "notes/work/${formatted_file_name}"
+#   nvim "notes/work/${formatted_file_name}"
+#   ;;
+# "")
+#   cd "$HOME/Documents/obsd" || exit
+#   touch "inbox/${formatted_file_name}"
+#   nvim "inbox/${formatted_file_name}"
+#   ;;
+# *)
+#   echo "Error: A file name must be set, e.g. on \"the wonderful thing about tiggers\"."
+#   exit 1
+#   ;;
+# esac
 
-touch "inbox/${formatted_file_name}"
-nvim "inbox/${formatted_file_name}"
+
+cd "$HOME/Documents/obsd" || exit
+
+if [ "$1" = "work" ]; then
+  file_name=$(echo "$2" | tr ' ' '-')
+  formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md
+  touch "notes/work/${formatted_file_name}"
+  nvim "notes/work/${formatted_file_name}"
+else
+  file_name=$(echo "$1" | tr ' ' '-')
+  formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md
+  touch "inbox/${formatted_file_name}"
+  nvim "inbox/${formatted_file_name}"
+fi
