save

diff --git a/scripts/install-golang b/scripts/install-golang
--- a/scripts/install-golang
+++ b/scripts/install-golang
@@ -1,24 +1,47 @@
 #!/usr/bin/env bash
 
-install-golang() {
+export GOOS=linux
 
-	if [[ $OSTYPE =~ ^darwin ]]; then
-		brew install golang
-		return
-	fi
+case "$(uname -m)" in
+x86_64) GOARCH="amd64" ;;
+aarch64) GOARCH="arm64" ;;
+*)
+	echo "Unsupported architecture"
+	exit 1
+	;;
+esac && export GOARCH
 
-	if [[ $OSTYPE =~ ^msys ]]; then
-		winget install --id golang.go
-		return
-	fi
+true "${TARGETDIR:="$HOME/.local"}"
 
-	if type apt-get &>/dev/null; then
-		sudo apt-get install -y golang
-		return
-	fi
-
-	echo "OS unsupported by this installer: $OSTYPE"
-
+lookup_file() {
+	curl -sSL "https://go.dev/dl/?mode=json" |
+		jq -r '.[0].files[]
+       | select(.os == "'"$GOOS"'")
+       | select(.arch == "'"$GOARCH"'")
+       | .filename'
 }
 
-install-golang
+fetch() {
+	local filename
+	filename="$(lookup_file)"
+	[[ -z "$filename" ]] && echo "unable to fetch filename" 1>&2 && return 1
+	local path="/tmp/$filename"
+	[[ -n "$DOWNLOADS" ]] && [[ -d "$DOWNLOADS" ]] && path="$DOWNLOADS/$filename"
+	curl -L "https://go.dev/dl/$filename" -o "$path"
+	echo "$path"
+}
+
+install_latest_go() {
+	local dir="$1" path
+	[[ -z "$dir" ]] && dir="$TARGETDIR"
+	[[ -z "$dir" ]] && dir="$HOME/.local"
+	mkdir -p "$dir" 2>/dev/null
+	path="$(fetch)"
+	[[ -z "$path" ]] && echo "unable to fetch go tarball" 1>&2 && return 1
+	rm -rf "$dir/go" && tar -C "$dir" -xzf "$path" # rm is required by instructions
+	echo "Add $dir/go/bin to your path and optionally set GOBIN=~/.local/bin" 1>&2
+	rm "$path"
+}
+
+install_latest_go "$@"
+
